### ISSUE TITLE
ERROR: script.module.thetvdb

### ISSUE THREAD

**Issue by abeksis** [kodi-community-addons/script.module.thetvdb#1]
21:48:09.578 T:123145405247488   ERROR: script.module.thetvdb --> Exception in get_data --> ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=20)",),)
21:48:38.865 T:123145400418304  NOTICE: Skin Helper Widgets --> Backgroundservice stopped
21:48:42.705 T:123145403637760 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
21:48:50.263 T:123145405247488   ERROR: script.module.thetvdb --> Exception in get_data --> ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=20)",),)
21:48:54.834 T:123145391218688   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://thetvdb.com/banners/episodes/305719/5603948.jpg
21:49:54.639 T:123145405247488   ERROR: script.module.thetvdb --> Exception in get_data --> ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=20)",),)

**Comment by marcelveldt** [comment]
Nothing wrong with that. TVDB api was down at that moment, that's why there was an read time out
