### ISSUE TITLE
[BUG] KODI_LANGUAGE  

### ISSUE THREAD

**Issue by tyl0re** [kodi-community-addons/script.module.thetvdb#5]
When Swiching the Language in Kodi the Addon still get the Old Content, its because the Variable 
KODI_LANGUAGE isn't used on simplecache hash

**Comment by marcelveldt** [comment]
Hmmm, yes that is true. A bit of an edge case but I can fix it.

**Comment by tyl0re** [comment]
Thanks, Not to Common. Default Kodi Installation ist English. So English is used. If you get the wrong result you switch the Language, and still get the wrong results

**Comment by marcelveldt** [comment]
Hi, I will work on this later this week. Been busy lately with other stuff

**Comment by marcelveldt** [comment]
just fixed this in the code
